<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>br.com.segue-me</groupId>
	<artifactId>segue-me</artifactId>
	<version>3.4.0</version>
	<packaging>war</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	    <maven.compiler.source>1.8</maven.compiler.source>
	    <maven.compiler.target>1.8</maven.compiler.target>
	    <maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	    <build.timestamp>${maven.build.timestamp}</build.timestamp>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>6.1</version>
		</dependency>

		<dependency>
			<groupId>org.primefaces.themes</groupId>
			<artifactId>paradise</artifactId>
			<version>1.0.1</version>
		</dependency>

		<dependency>
			<groupId>org.omnifaces</groupId>
			<artifactId>omnifaces</artifactId>
			<version>2.6.5</version>
		</dependency>

		<!-- Usado para geração de arquivos Excel -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.11</version>
		</dependency>

		<!-- Usado para geração de arquivos PDF -->
		<dependency>
			<groupId>com.lowagie</groupId>
			<artifactId>itext</artifactId>
			<version>2.1.7</version>
		</dependency>


		<dependency>
			<groupId>org.jboss.logging</groupId>
			<artifactId>jboss-logging</artifactId>
			<version>3.3.1.Final</version>
		</dependency>
		<!-- Implementacao do Bean Validation -->
		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>6.0.5.Final</version>
			<scope>compile</scope>
		</dependency>


		<!-- Núcleo do Hibernate -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>5.2.12.Final</version>
			<scope>compile</scope>
		</dependency>

		<!-- Implementação de EntityManager da JPA -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>5.2.12.Final</version>
			<scope>compile</scope>
		</dependency>

		<!-- Pool de conexoes com C3P0 -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-c3p0</artifactId>
			<version>5.2.12.Final</version>
			<scope>compile</scope>
		</dependency>

		<!-- Driver JDBC do MySQL -->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.34</version>
		</dependency>

		<!-- Weld (implementação do CDI) -->
		<dependency>
			<groupId>org.jboss.weld.servlet</groupId>
			<artifactId>weld-servlet</artifactId>
			<version>2.4.5.Final</version>
		</dependency>


		<!-- Weld depende do Jandex -->
		<dependency>
			<groupId>org.jboss</groupId>
			<artifactId>jandex</artifactId>
			<version>2.0.4.Final</version>
		</dependency>

		<!-- Mojarra (implementacao do JSF) -->
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.faces</artifactId>
			<version>2.2.13</version>
		</dependency>

		<!-- Log4J -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jcl</artifactId>
			<version>2.7</version>
		</dependency>

		<!-- Commons Logging (abstrai a implementação de logging) -->
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>

		<!-- Commons Lang (utilidades) -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.1</version>
		</dependency>

		<!-- Abstração para envio de e-mails -->
		<dependency>
			<groupId>com.outjected</groupId>
			<artifactId>simple-email</artifactId>
			<version>0.2.5-SNAPSHOT</version>
		</dependency>

		<!-- Requerido para envio de e-mails -->
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.7</version>
		</dependency>

		<!-- Usamos para templates de emails -->
		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.7</version>
		</dependency>

		<!-- Usamos para formatar números em templates -->
		<dependency>
			<groupId>velocity-tools</groupId>
			<artifactId>velocity-tools-generic</artifactId>
			<version>1.1</version>
		</dependency>

		<!-- Spring Security (autenticação e autorização) -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
			<version>4.1.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
			<version>4.1.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>4.1.3.RELEASE</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports -->
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>6.20.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports-fonts -->
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-fonts</artifactId>
			<version>6.20.0</version>
		</dependency>
		
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>ComicSans</artifactId>
			<version>1.0.0</version>
		</dependency>

		<!-- API de Servlet -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
		</dependency>

		<dependency>
			<groupId>xml-apis</groupId>
			<artifactId>xml-apis</artifactId>
			<version>2.0.2</version>
		</dependency>

		<dependency>
			<groupId>postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.1-901.jdbc4</version>
		</dependency>

		<!-- JAXB API: removido do JDK no Java 9+, necessário para Hibernate 5.2 em Java 11 -->
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>

	</dependencies>


		<build>
		<finalName>segue-me</finalName>
		<resources>
			<!-- Filtra APENAS o application.properties (para resolver ${project.version}
			     e ${maven.build.timestamp}). Nunca filtrar a pasta inteira: há .jasper
			     binários e templates Velocity que seriam corrompidos. -->
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>application.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>application.properties</exclude>
				</excludes>
			</resource>
		</resources>
	    <plugins>
	        <plugin>
	            <groupId>org.apache.maven.plugins</groupId>
	            <artifactId>maven-war-plugin</artifactId>
	            <version>3.3.1</version> <!-- ou uma versão mais recente -->
	            <configuration>
                	<source>1.8</source>
                	<target>1.8</target>
            	</configuration>
	        </plugin>
	        <!-- Expõe o hash do commit (git.commit.id.abbrev) para o filtering do
	             application.properties. Versão 4.9.10 = última compatível com Java 8. -->
	        <plugin>
	            <groupId>pl.project13.maven</groupId>
	            <artifactId>git-commit-id-plugin</artifactId>
	            <version>4.9.10</version>
	            <executions>
	                <execution>
	                    <id>get-git-info</id>
	                    <phase>initialize</phase>
	                    <goals>
	                        <goal>revision</goal>
	                    </goals>
	                </execution>
	            </executions>
	            <configuration>
	                <failOnNoGitDirectory>false</failOnNoGitDirectory>
	                <generateGitPropertiesFile>false</generateGitPropertiesFile>
	                <abbrevLength>7</abbrevLength>
	                <includeOnlyProperties>
	                    <includeOnlyProperty>^git.commit.id.abbrev$</includeOnlyProperty>
	                </includeOnlyProperties>
	            </configuration>
	        </plugin>
	    </plugins>
	</build>


	<repositories>
		<repository>
			<id>prime-repo</id>
			<name>PrimeFaces Maven Repository</name>
			<url>https://repository.primefaces.org</url>
			<layout>default</layout>
		</repository>
	</repositories>

</project>