# JSF em modo Development: mensagens de erro detalhadas na UI
javax.faces.PROJECT_STAGE=Development

# Locale pt_BR
user.language=pt
user.country=BR
user.timezone=America/Sao_Paulo

# Encoding padrão
file.encoding=UTF-8
